kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-apiserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kube-apiserver
  template:
    metadata:
      labels:
        app: kube-apiserver
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kube-apiserver
        image: ${HYPERKUBE_IMAGE}
        command:
        - hyperkube
        - kube-apiserver
        args:
        - "--openshift-config=/etc/kubernetes/config.yaml"
        workingDir: /var/log/kube-apiserver
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: 6443
            path: healthz
          initialDelaySeconds: 45
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            scheme: HTTPS
            port: 6443
            path: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: secret
        - mountPath: /var/log/kube-apiserver/
          name: logs
      volumes:
      - secret:
          secretName: kube-apiserver
        name: secret
      - emptyDir: {}
        name: logs
