---
apiVersion: v1
kind: Secret
metadata:
  name: hypershift-user-data
  namespace: openshift-machine-api
stringData:
  disableTemplating: "true"
  userData: |-
    {"ignition":{"config":{"append":[{"source":"s3://cewong-dev/final.ign","verification":{}}]},"security":{},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cewong-cb8cp
  name: cewong-cb8cp-hypershift-us-east-1a
  namespace: openshift-machine-api
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cewong-cb8cp
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/cluster-api-machineset: cewong-cb8cp-hypershift-us-east-1a
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: cewong-cb8cp
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cewong-cb8cp-hypershift-us-east-1a
    spec:
      metadata:
        creationTimestamp: null
      providerSpec:
        value:
          ami:
            id: ami-046fe691f52a953f9
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 120
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cewong-cb8cp-worker-profile
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-1a
            region: us-east-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cewong-cb8cp-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - cewong-cb8cp-private-us-east-1a
          tags:
          - name: kubernetes.io/cluster/cewong-cb8cp
            value: owned
          userDataSecret:
            name: hypershift-user-data
